version: "3"

services:
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: postgres/
    networks:
      - default
    expose:
      - 5432
    ports:
      - 5432:5432
  chat-server:
    build: avito
    depends_on:
      - db
    container_name: chat_server_avito
    restart: always
    ports:
      - "9000:9000"
    networks:
      - default